---
booktitle: Proceedings of the Eleventh International Conference on Artificial Intelligence
  and Statistics
series: Proceedings of Machine Learning Research
issn: 1938-7228
logo: SAIS_logo.jpg
volume: 2
year: '2007'
start: 2007-03-21
end: 2007-03-24
published: 2007-03-11
shortname: AISTATS
comments: false
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: pmlr
bibsource: http://jmlr.csail.mit.edu/proceedings/
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
id: MeilaMSX2007
month: 0
cycles: false
editor:
- given: Marina
  family: Meila
- given: Xiaotong
  family: Shen
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Eleventh International Conference on Artificial Intelligence and Statistics
    Held in San Juan, Puerto Rico on 21-24 March 2007

  Published as Volume 2 by the Proceedings of Machine Learning Research on 11 March 2007.

  Volume Edited by:
    Marina Meila
    Xiaotong Shen

  Series Editors:
    Neil D. Lawrence
date_str: 21--24 Mar
url: http://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v2"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
ghub:
  edit: true
  repository: v2
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
conference:
  name: Artificial Intelligence and Statistics
  url: http://aistats.org/aistats2007/
  location: San Juan, Puerto Rico
  dates:
  - 2007-03-21
  - 2007-03-22
  - 2007-03-23
  - 2007-03-24
  number: 11
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
